#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pkill dunst
pkill lxpolkit

bspc monitor -d 1 2 3 4

bspc config border_width         0
bspc config window_gap           20
bspc config left_padding         0
bspc config right_padding        0
bspc config bottom_padding       5
bspc config top_padding          0
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color   "#3c3836"
bspc config active_border_color   "#3c3836"
bspc config focused_border_color  "#3c3836"
bspc config focus_follows_pointer true

bspc rule -a feh state=floating center=on border=off rectangle=1280x720+0+0
bspc rule -a Catfish state=floating center=on rectangle=960x540+0+0
bspc rule -a Steam state=floating center=on follow=on border=off
bspc rule -a Gpick state=floating center=on rectangle=960x540+0+0
bspc rule -a Guvcview state=tiled
bspc rule -a Gnome-network-displays state=floating center=on

~/.config/polybar/launch.sh &

feh --bg-fill ~/Pictures/Wallpapers/4647404.png &

picom -b &

/usr/bin/lxpolkit &

pkill locker.sh
locker.sh &

#autovpn.sh &
